// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDuYktjTNLv7HOak8y9z244r5MHjZ1vs',
    appId: '1:39689455124:web:7457c310aceb22dd8a0901',
    messagingSenderId: '39689455124',
    projectId: 'foodapp-805f2',
    authDomain: 'foodapp-805f2.firebaseapp.com',
    storageBucket: 'foodapp-805f2.appspot.com',
    measurementId: 'G-Y76RGQCNCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1gRf1_gxEMtR7S1LyUPE4JaY5BbBjCa4',
    appId: '1:39689455124:android:73f611e33a89733e8a0901',
    messagingSenderId: '39689455124',
    projectId: 'foodapp-805f2',
    storageBucket: 'foodapp-805f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoqexUg-kZ0CUdCkIa_n4s15QBvG9eDY',
    appId: '1:39689455124:ios:28a20dc4d252e9d48a0901',
    messagingSenderId: '39689455124',
    projectId: 'foodapp-805f2',
    storageBucket: 'foodapp-805f2.appspot.com',
    iosClientId: '39689455124-em7jumjnm64pjc084uoqki6liohp7ja4.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoqexUg-kZ0CUdCkIa_n4s15QBvG9eDY',
    appId: '1:39689455124:ios:28a20dc4d252e9d48a0901',
    messagingSenderId: '39689455124',
    projectId: 'foodapp-805f2',
    storageBucket: 'foodapp-805f2.appspot.com',
    iosClientId: '39689455124-em7jumjnm64pjc084uoqki6liohp7ja4.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
